# Numpy

In [3]:
# install numpy
pip install numpy

In [4]:
import numpy as np

In [9]:
# Initializing from Python List
A = np.array([1,4,9,3,2])
print ('1D array in numpy is',A)
print ('dtype of the numpy array is',(A.dtype))
print ('shape of the numpy array is',A.shape)

1D array in numpy is [1 4 9 3 2]
dtype of the numpy array is int32
shape of the numpy array is (5,)


## Numpy array

How to create array in numpy

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

arange() will create arrays with regularly incrementing values.

In [3]:
# creatimg 2D array 
D_2 = np.array([[1,2,3] , [4,5,6]])
D_2


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# for finding shape
print("shape of an array" , D_2.shape)

shape of an array (2, 3)


**How to add two arrays together**

In [5]:
arr1 = np.array([[1,2,3] , [4,5,6]])
arr2 = np.array([[7,8,9] , [10,11,12]])

# we can add arr2 as rows to the end of arr1
# axis 0 = rows
ARR = arr1+arr2
print(ARR)
np.concatenate((arr1 , arr2) , axis =0)

[[ 8 10 12]
 [14 16 18]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
# we can add arr2 as columns to end of arr1
# axis 1 = columns

np.concatenate((arr1 , arr2) , axis =1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

**How to delete array in numpy**

In [9]:
# [1,2,3] , [4,5,6]])
del_arr1 = np.delete(arr1 , 2 , axis =1)
del_arr1

array([[1, 2],
       [4, 5]])

In [15]:
del_arr2 = np.delete(arr2 , 1 , axis =0)
del_arr2

array([[7, 8, 9]])

**Insert value into array**

In [16]:
arr = np.array([[2,4,8] , [3,6,9]])


# To insert at given index 

arr = np.insert(arr , 6 , 12 )


# To insert at beginning 
arr = np.insert(arr , 0 , 1)
arr

array([ 1,  2,  4,  8,  3,  6,  9, 12])

**Slicing in array**

In [18]:
# slicing 1 to 5 gives us : [1 through 4]
arr[1:5]

array([2, 4, 8, 3])

In [19]:
# if we do this, we are giving k, which is the step function. 
#in this case step by 2
arr[1:6:2]

array([2, 8, 6])

In [13]:
array1 = np.arange(0,20,3)
print ('before reversing',array1)
array2 = array1[::-1]
print ('Elements  in reverse is',array2)

before reversing [ 0  3  6  9 12 15 18]
Elements  in reverse is [18 15 12  9  6  3  0]


In [11]:
d2 = np.arange(16).reshape(4,4)
d2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Matrix Operation

In [24]:
a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
A = np.mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [13]:
A = np.mat('1,2,4;2,5,3;7,8,9')
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [10]:
matrix_0 = np.zeros(shape=(3,5))
print(matrix_0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
matrix_1 = np.ones(shape=(3,2))
print(matrix_1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
#Using numpy.random.random
mat1 = np.random.random(size=(3,4))
print (mat1)
mat2 = np.random.randint(low=0,high=2,size=(3,4))
print (mat2)
mat3 = np.random.randn(3,4)
print (mat3)

[[0.98654299 0.61790913 0.62945986 0.76172219]
 [0.16610172 0.15825002 0.78625597 0.51870997]
 [0.5545985  0.60911    0.26662096 0.24824894]]
[[0 1 0 1]
 [0 1 0 0]
 [1 1 0 0]]
[[ 0.96642455  2.26567367 -1.04317709  0.76608953]
 [-0.02185583 -0.12411676 -0.07553759 -0.47925059]
 [-0.317201   -0.15996539 -1.21639591  0.05351602]]


In [15]:
#Horizontal Matrix Splitting
matr = np.random.randint(0,6,(3,7))
splt1,splt2,splt3 = np.hsplit(matr,[4,6])
print ('Original matrix of shapen is ',(matr.shape,matr))
print ('First split of shape is ',(splt1.shape,splt1))
print ('Second split of shape is',(splt2.shape,splt2))
print ('Third split of shape is ',(splt3.shape,splt3))

Original matrix of shapen is  ((3, 7), array([[1, 4, 4, 3, 5, 4, 0],
       [5, 4, 1, 5, 2, 5, 3],
       [3, 5, 3, 1, 1, 3, 1]]))
First split of shape is  ((3, 4), array([[1, 4, 4, 3],
       [5, 4, 1, 5],
       [3, 5, 3, 1]]))
Second split of shape is ((3, 2), array([[5, 4],
       [2, 5],
       [1, 3]]))
Third split of shape is  ((3, 1), array([[0],
       [3],
       [1]]))


In [16]:
#vertical Matrix Splitting 
sp1,sp2 = np.vsplit(matr,[1])
print ('Original matrix of shape is ',(matr.shape,matr))
print ('First split of shape is',(sp1.shape,sp1))
print ('Second split of shape is',(sp2.shape,sp2))

Original matrix of shape is  ((3, 7), array([[1, 4, 4, 3, 5, 4, 0],
       [5, 4, 1, 5, 2, 5, 3],
       [3, 5, 3, 1, 1, 3, 1]]))
First split of shape is ((1, 7), array([[1, 4, 4, 3, 5, 4, 0]]))
Second split of shape is ((2, 7), array([[5, 4, 1, 5, 2, 5, 3],
       [3, 5, 3, 1, 1, 3, 1]]))


In [26]:
x = np.array([[4], [2], [3]])
x

array([[4],
       [2],
       [3]])

In [27]:
A * x

matrix([[20],
        [27],
        [71]])

In [28]:
print(A * A.I)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  2.08166817e-17]
 [ 2.22044605e-16 -8.32667268e-17  1.00000000e+00]]


In [29]:
print(A ** 3)


[[ 443  654  678]
 [ 489  731  741]
 [1269 1866 1919]]


**Sorting in array**

In [33]:
weights = np.array([20, 93, 53, 61])
sorted(weights)

[20, 53, 61, 93]

In [34]:
sorted(weights , reverse = True)

[93, 61, 53, 20]

## Statistical Function

np.mean(data,axis=0)
np.var(data,axis=0)
np.sum(data,axis=0)
np.max(data,axis=0)
np.min(data,axis=0)
np.percentile(data, percentage,axis=0)

In [17]:

matrix = np.arange(9).reshape((3,3))

print ('Original matrix is ',matrix)

print ('Overall mean of matrix is ',np.mean(matrix))
print ('Row mean of matrix is ',np.mean(matrix, axis=0))
print ('Column mean of matrix is',np.mean(matrix, axis=1))

print ('---------------------------\n')

print ('Overall varience of matrix is',np.var(matrix))
print ('Overall sum of matrix is',np.sum(matrix))
print ('Overall min of matrix is',np.min(matrix))
print ('Overall max of matrix is ',np.max(matrix))

print ('-------------------------------------\n')

marks = np.array([30,31,32,40,90,95,97,98,99,100])
print ('Marks =',marks)
print ('Overall 30 percent quantile of marks is',(str(np.percentile(marks,30))))

Original matrix is  [[0 1 2]
 [3 4 5]
 [6 7 8]]
Overall mean of matrix is  4.0
Row mean of matrix is  [3. 4. 5.]
Column mean of matrix is [1. 4. 7.]
---------------------------

Overall varience of matrix is 6.666666666666667
Overall sum of matrix is 36
Overall min of matrix is 0
Overall max of matrix is  8
-------------------------------------

Marks = [ 30  31  32  40  90  95  97  98  99 100]
Overall 30 percent quantile of marks is 37.599999999999994
